project:
  type: website

website:
  page-footer: "[![](https://img.shields.io/badge/license-CC--4.0--BY--SA-lightgrey)](https://creativecommons.org/licenses/by/4.0/deed.en) Vic Nagel"
  title: "Vic Nagel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



