---
title: "CV"
format: html
editor: visual
---

## Education

August 2022 - June 2024: Master at Sciences Po Paris - School of Research in Sociology

> 

January 2022 - June 2022: Erasmus exchange in the University of Glasgow

> 

September 2019 - June 2022: Bachelor at Sciences Po Nancy

> 

September 2019 - June 2021: Undergraduate in law at the Université de Lorraine

>

June 2019: Lycée Franco-Allemand - Buc


## Experiences

June 2024: Ecole d'été des méthodes mixtes

June 2024: International Conference on Social Stress Research

2023 - 2024: Research assistant at the Collège de France with Colombe Saillard

2023: Research assistant at Sciences Po with Marta Dominguez

## Qualification

### Quantitative methods with R and HTML

-   Statistical description
-   Panel analysis
-   Statistical inference
-   Social network analysis
-   Visualisation
-   Textual analysis
-   Web scraping

### Qualitative methods

-   Structured and semi-structured interviews
-   Participant and non participant ethnography
-   Digital ethnography

### Fields

-   Gender and sexuality
-   Social inequality
-   Sexual violence
-   Disability studies
-   Mental health

